[package]
name = "r9ir"
version = "1.0.0"
authors = ["kawakami <kawakami.ozone@gmail.com>"]
description = "Rewrite 9cc in Rust"
license = "MIT"
documentation = "https://docs.rs/r9ir"

[dependencies]

